sync:
  defaults:
    ignore:
      paths:
        # 版本控制
        - ".git"
        - ".svn"
        - ".hg"
        - ".bzr"
        
        # Node.js
        - "node_modules"
        - "npm-debug.log*"
        - "yarn-debug.log*"
        - "yarn-error.log*"
        - ".npm"
        - ".yarn"
        
        # Python
        - "__pycache__"
        - "*.pyc"
        - "*.pyo"
        - "*.egg-info"
        - ".venv"
        - "venv"
        - ".python-version"
        
        # 构建输出
        - "build"
        - "dist"
        - "out"
        - "target"
        # - "bin"
        - "obj"
        
        # 缓存和临时文件
        - ".cache"
        - ".tmp"
        - "tmp"
        - "temp"
        - "*.tmp"
        - "*.temp"
        - "*.log"
        - "logs"
        
        # 系统文件
        - ".DS_Store"
        - "Thumbs.db"
        - "desktop.ini"
        - "*.swp"
        - "*.swo"
        - "*~"
        
        # IDE和编辑器
        - ".vscode"
        - ".idea"
        - "*.sublime-project"
        - "*.sublime-workspace"
        - ".vs"
        
        # 数据库
        - "*.db"
        - "*.sqlite"
        - "*.sqlite3"
        
        # 压缩文件
        - "*.zip"
        - "*.tar.gz"
        - "*.rar"
        - "*.7z"
        
        # 媒体文件（可选，根据需要调整）
        - "*.mp4"
        - "*.avi"
        - "*.mkv"
        - "*.mov"

        # 模型文件
        - "*.pth"
        - "*.ckpt"
        - "*.pickle"
        - "*.pt"
        - "*.pkl"
        - "*.pth.tar"
        - "*.ckpt.tar"
        - "*.pickle.tar"
        - "*.pt.tar"
        - "*.pkl.tar"

        # 文档文件（可选，根据需要调整）
        # - "vis"
